FROM nginx:alpine

# Copy all files from your local frontend folder into Nginx's public HTML directory
COPY . /usr/share/nginx/html

# Expose port 80 inside the container
EXPOSE 80

# Nginx starts automatically, no CMD statement required
