services:
  db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: tasksdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
